#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Embed the reviewed Apple5 shader, or check that runtime source is identical."""
import argparse
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT/'native/apple/shaders/wavelet_dequant_apple5.metal'
HEADER = ROOT/'native/apple/PyroWaveApple5Source.h'


def content():
    shader = SOURCE.read_text()
    if ')PWAPPLE5"' in shader:
        raise RuntimeError('Shader contains the raw-string delimiter.')
    return ('// Generated by tools/embed_apple5_shader.py. Do not edit.\n'
            '// Copyright (c) 2026 Hans-Kristian Arntzen\n'
            '// SPDX-License-Identifier: MIT\n#pragma once\n'
            'static const char wavelet_dequant_apple5_msl_source[] = R"PWAPPLE5(\n'
            + shader + ')PWAPPLE5";\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    if parser.parse_args().check:
        if not HEADER.exists() or HEADER.read_text() != content():
            raise SystemExit('Apple5 embedded shader differs; run tools/embed_apple5_shader.py.')
    else:
        HEADER.write_text(content())
